account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('index/', views.index, name='index')
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns =[
    path('', views.index, name='index'),
    path('post_list/', views.post_list, name='post_list'),
    path('post_detail/<int:year>/<int:month>/<int:day>/<slug:post_slug>', views.post_detail, name='post_detail'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account'))
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('account/', include('account.urls', namespace='account'))
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        {% block  statics %}{% endblock %}
    </head>
    <body>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                            data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="{% url 'blog:index' %}">王俊翰的博客</a>
                </div>

                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li{% ifequal selected 'index' %} class="active"{% endifequal %}>
                            <a href="{% url 'blog:index' %}">首页</a>
                        </li>
                        <li {% ifequal selected 'post_list' %} class="active"{% endifequal %}>
                            <a href="{% url 'blog:post_list' %}">博客列表</a>
                        </li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if request.user.is_authenticated %}
                            <li><a href="{% url 'account:logout' %}">退出登录</a></li>
                        {% else %}
                            <li><a href="{% url 'account:login' %}">注册/登录</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>

        <div class='main'>
            {% block body %}{% endblock %}
        </div>

        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    王俊翰的博客
{% endblock %}

{% block body %}
    <h1 class="welcome">欢迎光临我的首页</h1>
{% endblock %}

templates/pagination.html
<div>
    <span>
        {% if page.has_previous %}
            <a href="？page={{page.previous_page_number}}">
                上一页
            </a>
        {% endif %}
    </span>
    <span>
        第{{page.number}}页,共{{page.paginator.num_pages}}页
    </span>
    <span>
        {% if page.has_next %}
            <a href="?page={{page.next_page_number}}">下一页</a>
        {% endif %}
    </span>
</div>

templates/paginator.html
<nav aria-label="Page navigation" id="pagintor-father">
    <ul class="pagination" id="pagintor-child">
        <li {% if not posts.has_previous %}class="disabled"{% endif %}>
            <a {% if  posts.has_previous %}
                href="?page={{ posts.previous_page_number }}"
            {% else %}
                href="#"
            {% endif %} aria-label="Previous">
                <span aria-hidden="true">&laquo;</span>
            </a>
        </li>
        {% for i in page_nums %}
            <li{% ifequal i page %} class="active"{% endifequal %}>
                <a href="?page={{ i }}">{{ i }}</a>
            </li>
        {% endfor %}
        <li {% if not posts.has_next %}class="disabled"{% endif %}>
            <a {% if posts.has_next %}
                href="?page={{ posts.next_page_number }}"
            {% else %}
                href="#"
            {% endif %} aria-label="Next">
                <span aria-hidden="true">&raquo;</span>
            </a>
        </li>
    </ul>
</nav>